#!/usr/bin/env bash
# Bash script that installs nginx server on ubuntu 20.04

sudo apt-get update -y
sudo apt-get install nginx -y

ufw allow 'Nginx HTTP'

echo "Hello World!" >> /var/www/html/index.nginx-debian.html

sudo service nginx start
