#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page

sudo apt-get update -y
sudo apt-get install nginx -y

ufw allow 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index

sudo sed -i '/listen 80 default_server;/ a \\trewrite /redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

sudo service nginx restart
