#!/usr/bin/env bash
#Bash script that pings an IP address passed as an argument

# ip variable for IP
IP="${1}"

# variable for the name of file
fn=$(basename "${BASH_SOURCE[@]}")

if ! [ "$IP" ]; then
	echo "Usage: ${fn} {IP_ADDRESS}"
else
	ping -c 5 "${IP}"
fi
