#!/usr/bin/env bash
# Program is used to manage script (manage_my_process)
#   arg `start` is passed
#     1. Startscript manage_my_process
#     2. Create file containings its PID in /var/run/my_process.pid
#     3. Display "manage_my_process started"
#   arg `stop` is passed
#     1. Stop script manage_my_process
#     2. Delete file /var/run/my_process.pid
#     3. Display "manage_my_process stopped"
#   arg `restart` is passed
#     1. Stop manage_my_process
#     2. Delete the file /var/run/my_process.pid
#     3. Start script manage_my_process
#     4. Create file with its PID in /var/run/my_process.pid
#     5. Displays "manage_my_process restarted"
#   For any other args passed we see display of
#  Use in script manage_my_process {start|stop|restart}

if [ "${1}" == "start" ]
then
    ./manage_my_process &
    touch /var/run/my_process.pid
    echo "$!" > /var/run/my_process.pid
    echo "manage_my_process started"

elif [ "${1}" == "stop" ]
then
    echo "manage_my_process stopped"
    kill "$(cat /var/run/my_process.pid)"
    rm /var/run/my_process.pid

elif [ "${1}" == "restart" ]
then
    kill "$(cat /var/run/my_process.pid)"
    rm /var/run/my_process.pid
    ./manage_my_process &
    touch /var/run/my_process.pid
    echo "$!" > /var/run/my_process.pid
    echo "manage_my_process restarted"

else
    echo "Usage: manage_my_process {start|stop|restart}"
fi
