#!/usr/bin/env bash
# Fizzbuzz program of numbers 1 to 100

for Number in {1..100}
do
  if (( Number % 3 == 0 && Number % 5 == 0 ))
  then
    echo "FizzBuzz"

  elif (( Number % 3 == 0 ))
  then
    echo "Fizz"

  elif (( Number % 5 == 0 ))
  then
    echo "Buzz"

  else
    echo "$Number"
  fi

done
