#!/usr/bin/env bash
#Displays Best Sch using while and bad luck for 4, good luck for 8

counter=1
while((counter<=10))
do
    if [ $counter -eq 4 ]
    then
        echo "bad luck"
    elif [ $counter -eq 8 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((counter++))
done
