#!/usr/bin/env bash
#Program uses nested while to display hours and minutes

hour=0
while((hour<=12))
do
    echo "Hour: $hour"
    minute=1
    while((minute<=59))
    do
        echo "$minute"
        ((minute++))
    done
    ((hour++))
done
