#!/usr/bin/env bash
# domain changes ips
#   127.0.0.1 home/localhost >> 127.0.0.2
#   157.240.11.35 for facebook.com >> 8.8.8.8

cp /etc/hosts ~/hosts.new
echo "127.0.0.2		localhost" > ~/hosts.new
echo "8.8.8.8		facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
