#!/usr/bin/env bash
# Displays all acive IPv4 addresses on IPv4 machine.

# using ifconfig but make ip a new cmd could go missing in some operating systems
# awk '{print $2}'

ip -4 -o addr show | awk '{print $4}' | cut -d "/" -f 1
