#!usr/bin/bash/env bash
# Script runs Nginx as nginx user and conf to listen to port 8080

pkill apache2
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
chmod 644 /etc/nginx/ngix.conf
sudo -u nginx service nginx restart
